# 自动生成：仅启用 CSV Provider 的最小配置
provider_priority:
  - csv

provider_configs:
  csv:
    csv_dir: "/home/evan/short_second_strategy/data/zipline_csv"
    allow_stub: false

enable_cache: true
cache_ttl_hours:
  1d: 24

conflict_threshold: 0.02
freshness_tolerance_days: 3

default_calendar: "XSHG"
default_exchange: "XSHE"
